package im.langchainjava.llm.entity;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A chat completion generated by GPT-3.5
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ChatCompletionChoice {

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    /**
     * The {@link ChatMessageRole#assistant} message which was generated.
     */
    ChatMessage message;

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    @JsonProperty("finish_reason")
    String finishReason;
}
